version: "3.9"
name: petclinic
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - RUN_MODE=docker
