config_name = "production"
service_port = 3000
tera_templates = "templates/**/*"

[database]
path = "db.sqlite"
connections = 8

[redis]
server = "localhost"
password = "redispass"

[session]
timeout = 108000
